//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOceanWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        public int fId { get; set; }

        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號為必要輸入。")]
        [StringLength(25, ErrorMessage = "帳號長度不可以超過25")]
        public string fUserId { get; set; }

        [DisplayName("密碼")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "密碼為必要輸入。")]
        public string fPwd { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名為必要輸入。")]
        [StringLength(25, ErrorMessage = "姓名長度不可以超過25")]
        public string fName { get; set; }

        [DisplayName("信箱")]
        [Required(ErrorMessage = "信箱為必要輸入。")]
        [EmailAddress]
        public string fEmail { get; set; }

        [DisplayName("電話")]
        public string fPhone { get; set; }
    }
}
