//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOceanWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tProduct
    {
        [DisplayName("產品流水編號")]
        public int fId { get; set; }

        [DisplayName("產品類別")]
        [Required(ErrorMessage = "產品類別為必要輸入。")]
        public int fCategory { get; set; }

        [DisplayName("產品編號")]
        [Required(ErrorMessage = "產品名稱為必要輸入。")]
        [StringLength(25, ErrorMessage = "產品名稱長度不可以超過25")]
        public string fPId { get; set; }

        [DisplayName("產品名稱")]
        [Required(ErrorMessage = "產品名稱為必要輸入。")]
        [StringLength(25, ErrorMessage = "產品名稱長度不可以超過25")]
        public string fName { get; set; }

        [DisplayName("產品說明")]
        [Required(ErrorMessage = "產品說明為必要輸入。")]
        [StringLength(250, ErrorMessage = "產品說明長度不可以超過250")]
        public string fDescription { get; set; }

        [DisplayName("產品價格")]
        [Required(ErrorMessage = "產品價格為必要輸入。")]
        [Range(0, 99999, ErrorMessage = "價格只能是 0 .. 99999。")]
        public int fPrice { get; set; }

        [DisplayName("產品圖片路徑")]
        public string fImagePath { get; set; }

        [DisplayName("產品供應狀態")]
        public bool fIsActiveFlag { get; set; }

        [DisplayName("")]
        public string Buy { get; set; }
    }
}
